title: Twileloop.SessionGuard
description: "A reactive event based state management framework that centralises application state and give callbacks on state updates across application."
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
github:
  zip_url: https://github.com/sangeethnandakumar/Twileloop.SessionGuard/releases
  tar_url: https://www.nuget.org/packages/Twileloop.SessionGuard
